-- Tabela de aulas
create table public.aulas (
  id integer generated by default as identity primary key,
  titulo text not null,
  descricao text not null,
  assunto text not null,
  url_video text not null,
  created_at timestamp with time zone default now(),
  ativo boolean default true
);

-- Tabela de comentários
create table public.comentarios (
  id integer generated by default as identity primary key,
  aula_id integer references public.aulas(id),
  usuario_id integer references public.usuarios(id),
  texto text not null,
  created_at timestamp with time zone default now(),
  ativo boolean default true
);
